import{createFileRoute}from"@tanstack/react-router";import{z}from"zod";import{database,requireSessionUser,verifyMutationRequest}from"@/lib/auth.server";
const subject=z.enum(["chemistry","physics","integrated"]),base=z.object({subject,grade:z.union([z.literal(10),z.literal(11),z.literal(12)]),title:z.string().trim().min(1).max(140)}),update=z.object({id:z.string().uuid(),title:z.string().trim().min(1).max(140).optional(),completed:z.boolean().optional()}).refine(v=>v.title!==undefined||v.completed!==undefined),remove=z.object({id:z.string().uuid()});type Row={id:string;subject:"chemistry"|"physics"|"integrated";grade:10|11|12;title:string;completed:number;position:number;created_at:string;updated_at:string};
const valid=(v:{subject:string;grade:number})=>v.subject==="integrated"?v.grade===10:[10,11,12].includes(v.grade),present=(r:Row)=>({...r,completed:Boolean(r.completed)});
function json(data:unknown,init:ResponseInit={}){const headers=new Headers(init.headers);headers.set("content-type","application/json; charset=utf-8");headers.set("cache-control","no-store");return new Response(JSON.stringify(data),{...init,headers})}
async function body(request:Request){if(Number(request.headers.get("content-length")??"0")>8192)throw new Response("الطلب كبير جدًا",{status:413});return request.json().catch(()=>null)}
export const Route=createFileRoute("/api/lessons")({server:{handlers:{
GET:async({request})=>{const user=await requireSessionUser(request),result=await database().prepare("SELECT id,subject,grade,title,completed,position,created_at,updated_at FROM lessons WHERE owner_id=? ORDER BY subject,grade,position,created_at").bind(user.id).all<Row>();return json({lessons:(result.results??[]).map(present)})},
POST:async({request})=>{verifyMutationRequest(request);const user=await requireSessionUser(request),parsed=base.safeParse(await body(request));if(!parsed.success||!valid(parsed.data))return json({error:"بيانات الدرس غير صالحة"},{status:400});const{subject,grade,title}=parsed.data,next=await database().prepare("SELECT COALESCE(MAX(position),-1)+1 AS value FROM lessons WHERE owner_id=? AND subject=? AND grade=?").bind(user.id,subject,grade).first<{value:number}>(),id=crypto.randomUUID(),now=new Date().toISOString(),position=Number(next?.value??0);await database().prepare("INSERT INTO lessons(id,owner_id,subject,grade,title,completed,position,created_at,updated_at) VALUES(?,?,?,?,?,0,?,?,?)").bind(id,user.id,subject,grade,title,position,now,now).run();return json({lesson:present({id,subject,grade,title,completed:0,position,created_at:now,updated_at:now})},{status:201})},
PATCH:async({request})=>{verifyMutationRequest(request);const user=await requireSessionUser(request),parsed=update.safeParse(await body(request));if(!parsed.success)return json({error:"تعذر تحديث الدرس"},{status:400});const current=await database().prepare("SELECT id,subject,grade,title,completed,position,created_at,updated_at FROM lessons WHERE id=? AND owner_id=?").bind(parsed.data.id,user.id).first<Row>();if(!current)return json({error:"الدرس غير موجود"},{status:404});const title=parsed.data.title??current.title,completed=parsed.data.completed===undefined?current.completed:Number(parsed.data.completed),now=new Date().toISOString();await database().prepare("UPDATE lessons SET title=?,completed=?,updated_at=? WHERE id=? AND owner_id=?").bind(title,completed,now,current.id,user.id).run();return json({lesson:present({...current,title,completed,updated_at:now})})},
DELETE:async({request})=>{verifyMutationRequest(request);const user=await requireSessionUser(request),parsed=remove.safeParse(await body(request));if(!parsed.success)return json({error:"تعذر حذف الدرس"},{status:400});await database().prepare("DELETE FROM lessons WHERE id=? AND owner_id=?").bind(parsed.data.id,user.id).run();return json({ok:true})}
}}});
