import type { D1Database } from "@cloudflare/workers-types";
import { setCookie } from "@tanstack/react-start/server";
import { bindings } from "@/lib/bindings.server";
const COOKIE="fl_session",EMBED_COOKIE="fl_session_embed",SESSION_DAYS=30,PBKDF2_ITERATIONS=100000,enc=new TextEncoder();
export type SessionUser={id:string;email:string};
export function database():D1Database{const db=bindings().DB;if(!db)throw new Error("Database binding is unavailable");return db}
function bytesToBase64(bytes:Uint8Array){let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)}
function base64ToBytes(value:string){const binary=atob(value);return Uint8Array.from(binary,c=>c.charCodeAt(0))}
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",enc.encode(value));return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}
function randomToken(bytes=32){const value=new Uint8Array(bytes);crypto.getRandomValues(value);return bytesToBase64(value).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
export async function hashPassword(password:string){const salt=new Uint8Array(16);crypto.getRandomValues(salt);const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations:PBKDF2_ITERATIONS},key,256);return{hash:bytesToBase64(new Uint8Array(bits)),salt:bytesToBase64(salt)}}
export async function verifyPassword(password:string,expectedHash:string,salt:string){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const saltBytes=base64ToBytes(salt);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:saltBytes.buffer as ArrayBuffer,iterations:PBKDF2_ITERATIONS},key,256));const expected=base64ToBytes(expectedHash);if(bits.byteLength!==expected.byteLength)return false;let mismatch=0;for(let i=0;i<bits.length;i++)mismatch|=bits[i]^expected[i];return mismatch===0}
export function verifyMutationRequest(request:Request){if(request.headers.get("x-following-lessons")!=="1")throw new Response("طلب غير صالح",{status:403});const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)throw new Response("طلب غير صالح",{status:403})}
function parseCookie(request:Request,name:string){const raw=request.headers.get("cookie")??"";for(const part of raw.split(";")){const[key,...rest]=part.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="))}return null}
export async function createSession(userId:string){const token=randomToken(),tokenHash=await sha256(token),expiresAt=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await database().prepare("INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,?)").bind(tokenHash,userId,expiresAt).run();return token}
export function setSessionCookies(token:string){const shared={path:"/",httpOnly:true,secure:true,maxAge:SESSION_DAYS*86400}as const;setCookie(COOKIE,token,{...shared,sameSite:"lax"});setCookie(EMBED_COOKIE,token,{...shared,sameSite:"none",partitioned:true})}
export function expireSessionCookies(){const shared={path:"/",httpOnly:true,secure:true,maxAge:0}as const;setCookie(COOKIE,"",{...shared,sameSite:"lax"});setCookie(EMBED_COOKIE,"",{...shared,sameSite:"none",partitioned:true})}
function sessionTokens(request:Request){return[parseCookie(request,COOKIE),parseCookie(request,EMBED_COOKIE)].filter((token):token is string=>Boolean(token))}
export async function getSessionUser(request:Request){for(const token of sessionTokens(request)){const tokenHash=await sha256(token),user=await database().prepare("SELECT users.id,users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND sessions.expires_at>?").bind(tokenHash,new Date().toISOString()).first<SessionUser>();if(user)return user}return null}
export async function requireSessionUser(request:Request){const user=await getSessionUser(request);if(!user)throw new Response("يلزم تسجيل الدخول",{status:401});return user}
export async function clearSession(request:Request){for(const token of new Set(sessionTokens(request)))await database().prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha256(token)).run()}
async function attemptKey(request:Request){const ip=request.headers.get("cf-connecting-ip")??"unknown",agent=request.headers.get("user-agent")?.slice(0,160)??"unknown";return sha256(`${ip}:${agent}`)}
export async function isRateLimited(request:Request){const key=await attemptKey(request),row=await database().prepare("SELECT attempts,window_start FROM auth_attempts WHERE attempt_key=?").bind(key).first<{attempts:number;window_start:string}>();return!!row&&Date.now()-Date.parse(row.window_start)<900000&&row.attempts>=8}
export async function recordAuthFailure(request:Request){const key=await attemptKey(request),now=new Date().toISOString(),row=await database().prepare("SELECT attempts,window_start FROM auth_attempts WHERE attempt_key=?").bind(key).first<{attempts:number;window_start:string}>();if(!row||Date.now()-Date.parse(row.window_start)>=900000)await database().prepare("INSERT INTO auth_attempts(attempt_key,attempts,window_start) VALUES(?,1,?) ON CONFLICT(attempt_key) DO UPDATE SET attempts=1,window_start=excluded.window_start").bind(key,now).run();else await database().prepare("UPDATE auth_attempts SET attempts=attempts+1 WHERE attempt_key=?").bind(key).run()}
export async function clearAuthFailures(request:Request){await database().prepare("DELETE FROM auth_attempts WHERE attempt_key=?").bind(await attemptKey(request)).run()}
const RECOVERY_ALPHABET="23456789ABCDEFGHJKMNPQRSTVWXYZ";
export function randomRecoveryCode(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);const chars=Array.from(bytes,b=>RECOVERY_ALPHABET[b%RECOVERY_ALPHABET.length]).join("");return chars.match(/.{1,4}/g)!.join("-")}
export function normalizeRecoveryCode(code:string){return code.trim().toUpperCase().replace(/[^A-Z0-9]/g,"")}
export async function hashRecoveryCode(code:string){return sha256(normalizeRecoveryCode(code))}
