import{createFileRoute}from"@tanstack/react-router";import{useEffect,useMemo,useState,type CSSProperties,type FormEvent}from"react";import{Atom,Check,CloudArrowDown,CloudCheck,Flask,Leaf,LockKey,MagnifyingGlass,PencilSimple,Plus,SignOut,Trash,WaveSine,X}from"@phosphor-icons/react";import{ScrollScrub}from"@/components/scroll-scrub/scroll-scrub";import{scrollScrubScenes,scrollScrubTheme}from"@/scroll-scrub-scenes";
export const Route=createFileRoute("/")({component:Index});type Subject="chemistry"|"physics"|"integrated";type Filter="all"|"open"|"done";type Lesson={id:string;subject:Subject;grade:10|11|12;title:string;completed:boolean;position:number;created_at:string;updated_at:string};
const subjects:Array<{id:Subject;name:string;note:string;grades:Array<10|11|12>}>=[{id:"chemistry",name:"الكيمياء",note:"المادة والتفاعلات",grades:[10,11,12]},{id:"physics",name:"الفيزياء",note:"الحركة والطاقة",grades:[10,11,12]},{id:"integrated",name:"العلوم المتكاملة",note:"روابط العلوم",grades:[10]}];
function SubjectIcon({subject}:{subject:Subject}){return subject==="chemistry"?<Flask weight="duotone"/>:subject==="physics"?<Atom weight="duotone"/>:<Leaf weight="duotone"/>}
function request(path:string,init:RequestInit={}){const headers=new Headers(init.headers);if(init.method&&init.method!=="GET"){headers.set("content-type","application/json");headers.set("x-following-lessons","1")}return fetch(path,{...init,headers,credentials:"include"})}
function Index(){return <main className="site-shell"><header className="site-nav"><a className="brand-lockup" href="#" aria-label="Following Lessons"><span className="brand-orbit"><span/></span><b>Following Lessons</b></a><a className="nav-entry" href="#workspace">افتح مساحة الدروس</a></header><section className="journey" aria-label="مقدمة متحركة"><ScrollScrub scenes={scrollScrubScenes} theme={scrollScrubTheme}/><a className="hero-entry" href="#workspace">ابدأ المتابعة <CloudArrowDown weight="bold"/></a></section><Workspace/></main>}
function Workspace(){const[auth,setAuth]=useState<"loading"|"guest"|"ready">("loading"),[setupRequired,setSetupRequired]=useState(false),[lessons,setLessons]=useState<Lesson[]>([]),[subject,setSubject]=useState<Subject>("chemistry"),[grade,setGrade]=useState<10|11|12>(10),[filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[sync,setSync]=useState<"idle"|"syncing"|"saved">("idle"),[error,setError]=useState("");
async function loadLessons(){setSync("syncing");const response=await request("/api/lessons");if(response.status===401){setAuth("guest");setSync("idle");return}if(!response.ok){setError("تعذر جلب الدروس. حاول مجددًا.");setSync("idle");return}const data=await response.json()as{lessons:Lesson[]};setLessons(data.lessons);setSync("saved");window.setTimeout(()=>setSync("idle"),1600)}
useEffect(()=>{void(async()=>{const response=await request("/api/auth");if(!response.ok){setAuth("guest");return}const data=await response.json()as{authenticated:boolean;setupRequired:boolean};setSetupRequired(data.setupRequired);setAuth(data.authenticated?"ready":"guest");if(data.authenticated)await loadLessons()})()},[]);
const selected=useMemo(()=>lessons.filter(l=>l.subject===subject&&l.grade===grade),[lessons,subject,grade]),visible=useMemo(()=>selected.filter(l=>(filter==="all"||(filter==="done"?l.completed:!l.completed))&&l.title.toLocaleLowerCase("ar").includes(query.trim().toLocaleLowerCase("ar"))),[selected,filter,query]),completed=selected.filter(l=>l.completed).length,percent=selected.length?Math.round(completed/selected.length*100):0;
if(auth==="loading")return <section id="workspace" className="workspace loading-shell" aria-label="جار التحميل"><div className="skeleton skeleton-banner"/><div className="skeleton-grid">{[1,2,3].map(i=><div className="skeleton skeleton-card" key={i}/>)}</div></section>;
if(auth==="guest")return <AuthPanel setupRequired={setupRequired} onReady={async()=>{setAuth("ready");setSetupRequired(false);await loadLessons()}}/>;
async function mutate(method:"POST"|"PATCH"|"DELETE",payload:unknown){setError("");setSync("syncing");const response=await request("/api/lessons",{method,body:JSON.stringify(payload)}),data=await response.json().catch(()=>({}))as{lesson?:Lesson;error?:string};if(!response.ok){setError(data.error??"تعذر حفظ التغيير");setSync("idle");return null}setSync("saved");window.setTimeout(()=>setSync("idle"),1300);return data.lesson??true}
async function addLesson(title:string){const result=await mutate("POST",{subject,grade,title});if(result&&result!==true)setLessons(current=>[...current,result]);return Boolean(result)}
async function updateLesson(id:string,patch:{title?:string;completed?:boolean}){const result=await mutate("PATCH",{id,...patch});if(result&&result!==true)setLessons(current=>current.map(l=>l.id===id?result:l))}
async function deleteLesson(id:string){const result=await mutate("DELETE",{id});if(result)setLessons(current=>current.filter(l=>l.id!==id))}
async function logout(){await request("/api/auth",{method:"POST",body:JSON.stringify({action:"logout"})});setLessons([]);setAuth("guest")}
const activeSubject=subjects.find(item=>item.id===subject)!;
return <section id="workspace" className="workspace"><div className="workspace-inner"><header className="workspace-banner"><div className="banner-copy"><span className="eyebrow">مساحة خاصة ومزامنة تلقائية</span><h2>مخطط الدروس</h2><p>اختر المادة والصف، ثم أضف الدروس وحدّث إنجازها بلمسة واحدة.</p></div><div className="progress-wrap" aria-label={`اكتمل ${percent}%`}><div className="progress-ring" style={{"--progress":`${percent*3.6}deg`}as CSSProperties}><strong>{percent}%</strong><span>مكتمل</span></div><div className="progress-caption"><b>{completed} من {selected.length}</b><span>في {activeSubject.name} للصف {grade}</span></div></div></header>
<div className="workspace-topline"><div className="sync-note" aria-live="polite">{sync==="syncing"?<><CloudArrowDown className="spin-soft"/> جار المزامنة</>:<><CloudCheck weight="fill"/> {sync==="saved"?"تم الحفظ":"محفوظ على أجهزتك"}</>}</div><div className="account-actions"><button type="button" onClick={()=>void loadLessons()} aria-label="تحديث الدروس"><CloudArrowDown/></button><button type="button" onClick={()=>void logout()}><SignOut/> خروج</button></div></div>
<nav className="subject-rail" aria-label="المواد">{subjects.map(item=>{const count=lessons.filter(l=>l.subject===item.id).length;return <button type="button" key={item.id} className={item.id===subject?"subject-card active":"subject-card"} onClick={()=>{setSubject(item.id);setGrade(item.grades[0]);setFilter("all")}}><span className="subject-number">0{subjects.indexOf(item)+1}</span><SubjectIcon subject={item.id}/><span><b>{item.name}</b><small>{item.note}</small></span><em>{count} درس</em></button>})}</nav>
<div className="lesson-workspace"><div className="lesson-heading"><div><h3>{activeSubject.name}</h3></div><div className="grade-tabs" aria-label="اختيار الصف">{activeSubject.grades.map(value=><button type="button" key={value} className={grade===value?"active":""} onClick={()=>setGrade(value)}>الصف {value}</button>)}</div></div><AddLesson onAdd={addLesson}/><div className="lesson-tools"><label className="search-box"><MagnifyingGlass/><span className="sr-only">ابحث عن درس</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث في الدروس"/></label><div className="filter-tabs">{([["all","الكل"],["open","قيد العمل"],["done","مكتمل"]]as Array<[Filter,string]>).map(([id,label])=><button type="button" className={filter===id?"active":""} onClick={()=>setFilter(id)} key={id}>{label}</button>)}</div></div>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="lesson-list">{visible.map((lesson,index)=><LessonRow key={lesson.id} lesson={lesson} index={index} onUpdate={updateLesson} onDelete={deleteLesson}/>)}{!visible.length&&<EmptyState hasLessons={selected.length>0}/>}</div></div></div></section>}
function AuthPanel({setupRequired,onReady}:{setupRequired:boolean;onReady:()=>Promise<void>}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function submit(event:FormEvent){event.preventDefault();setError("");setBusy(true);const response=await request("/api/auth",{method:"POST",body:JSON.stringify({action:setupRequired?"setup":"login",email,password})}),data=await response.json().catch(()=>({}))as{error?:string};if(!response.ok){setError(data.error??"تعذر تسجيل الدخول");setBusy(false);return}await onReady();setBusy(false)}return <section id="workspace" className="workspace auth-section"><div className="auth-shell"><div className="auth-visual"><img src="/assets/brand/cover-scene.png" alt="" role="presentation"/><div><WaveSine weight="duotone"/><span>مساحتك العلمية، على كل أجهزتك</span></div></div><form className="auth-card" onSubmit={e=>void submit(e)}><span className="auth-icon"><LockKey weight="duotone"/></span><h2>{setupRequired?"أنشئ حسابك الخاص":"مرحبًا بعودتك"}</h2><p>{setupRequired?"هذا الحساب يُنشأ مرة واحدة، وبعدها تصبح المساحة لك وحدك.":"سجّل الدخول لتظهر دروسك المحدثة على هذا الجهاز."}</p><label>البريد الإلكتروني<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>كلمة المرور<input type="password" autoComplete={setupRequired?"new-password":"current-password"} minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/><small>10 أحرف على الأقل</small></label>{error&&<p className="inline-error" role="alert">{error}</p>}<button className="auth-submit" disabled={busy}>{busy?"لحظة...":setupRequired?"إنشاء المساحة":"دخول"}</button></form></div></section>}
function AddLesson({onAdd}:{onAdd:(title:string)=>Promise<boolean>}){const[title,setTitle]=useState(""),[busy,setBusy]=useState(false);async function submit(event:FormEvent){event.preventDefault();const clean=title.trim();if(!clean)return;setBusy(true);if(await onAdd(clean))setTitle("");setBusy(false)}return <form className="add-lesson" onSubmit={e=>void submit(e)}><span><Plus weight="bold"/></span><label><span className="sr-only">اسم الدرس</span><input maxLength={140} value={title} onChange={e=>setTitle(e.target.value)} placeholder="اكتب اسم درس جديد"/></label><button disabled={busy||!title.trim()}>{busy?"يُضاف...":"إضافة الدرس"}</button></form>}
function LessonRow({lesson,index,onUpdate,onDelete}:{lesson:Lesson;index:number;onUpdate:(id:string,patch:{title?:string;completed?:boolean})=>Promise<void>;onDelete:(id:string)=>Promise<void>}){const[editing,setEditing]=useState(false),[draft,setDraft]=useState(lesson.title),[confirming,setConfirming]=useState(false);async function save(){const clean=draft.trim();if(clean&&clean!==lesson.title)await onUpdate(lesson.id,{title:clean});setEditing(false)}return <article className={lesson.completed?"lesson-row complete":"lesson-row"}><span className="lesson-index">{String(index+1).padStart(2,"0")}</span><button className="complete-toggle" type="button" onClick={()=>void onUpdate(lesson.id,{completed:!lesson.completed})} aria-label={lesson.completed?"إلغاء الاكتمال":"وضع علامة مكتمل"}>{lesson.completed&&<Check weight="bold"/>}</button><div className="lesson-name">{editing?<input aria-label="تعديل اسم الدرس" autoFocus maxLength={140} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void save();if(e.key==="Escape"){setDraft(lesson.title);setEditing(false)}}}/>:<button type="button" onClick={()=>void onUpdate(lesson.id,{completed:!lesson.completed})}><b>{lesson.title}</b><small>{lesson.completed?"اكتمل التصميم":"لم يكتمل بعد"}</small></button>}</div><div className="row-actions">{editing?<><button type="button" onClick={()=>void save()} aria-label="حفظ"><Check/></button><button type="button" onClick={()=>{setDraft(lesson.title);setEditing(false)}} aria-label="إلغاء"><X/></button></>:<button type="button" onClick={()=>setEditing(true)} aria-label="تعديل اسم الدرس"><PencilSimple/></button>}{confirming?<span className="delete-confirm"><button type="button" onClick={()=>void onDelete(lesson.id)}>حذف</button><button type="button" onClick={()=>setConfirming(false)}>إلغاء</button></span>:<button className="delete-trigger" type="button" onClick={()=>setConfirming(true)} aria-label="حذف الدرس"><Trash/></button>}</div></article>}
function EmptyState({hasLessons}:{hasLessons:boolean}){return <div className="empty-state"><img src="/assets/brand/empty-state.png" alt="" role="presentation"/><div><h4>{hasLessons?"لا توجد نتائج مطابقة":"ابدأ بأول درس"}</h4><p>{hasLessons?"غيّر البحث أو مرشح الحالة.":"اكتب اسم الدرس في الأعلى، ويمكنك إضافة أي عدد تحتاجه."}</p></div></div>}
